### ISSUE TITLE
Ensure Project level actions can run as part of another namespace besides Project

### ISSUE THREAD

**Issue by Eruanion** [aws/cta#423]
## Description
Currently a project level action needs to be run as such:

{
      "namespace": "Project",
      "Assembly": "Project",
      "Reference": "Project",
      "Type": "Project",
      "Actions": [
        {
          "Name": "ArchiveFiles",
          "Type": "Project",
          "Value": "",
          "Description": "Add NetTopologySuite.Geometries namespace"
        }
      ]
    }

This can cause issue if we need to perform a project level action based on another trigger such as the presence of a specific class.

We need to be able to run this action as part of any other rule.

## Solution idea(s)
The solution for this is modifying the AnalysisRun.cs class and including a section for project level actions as well.

**Comment by jonlouie** [comment]
Closing. Re-open if this is rule type is still needed
