### ISSUE TITLE
Query 

### ISSUE THREAD

**Issue by vvijayalakshmi21** [aws/cta#61]
Hi, is this tool usable as a stand alone utility without an aws account? 
What would be the pre requisites for 1) an individual 2) an organization?

Kindly help. 
Sorry for raising this as an issue. 
Couldn't find a q&a section.

Thanks in advance!

**Comment by marknfawaz** [comment]
Hello,

Thank you for reaching out. This tool can be used without an AWS account. For using the tool, you just have to abide by the licensing requirements stated here:

https://github.com/aws/cta/blob/main/LICENSE

Please let us know if you have any questions using the tool. Thanks again for reaching out.
