### ISSUE TITLE
System.Web Actions Conflicting with WebForms Porting Action

### ISSUE THREAD

**Issue by comsemer** [aws/cta#635]
## Describe the bug
While porting WebForms projects, actions executed for System.Web.IHttpHandler and System.Web.IHttpModule conflict with changes being made during WebForms porting. This conflict generates validation exceptions for the System.Web actions but still produces the correct porting results.

### Expected behavior
No validation exceptions should be generated, only 1 set of rules should be executed.

**Comment by jonlouie** [comment]
Closing- validation exceptions are not used
