### ISSUE TITLE
Allow users to use CSV based formats for rules

### ISSUE THREAD

**Issue by marknfawaz** [aws/cta#99]
## Description
Our rules can be simplified into a simple format, which is the node to match against and what actions to run when this node is found. Using this concept, our rules can be written in a simpler CSV format to allow users to easily add replacements they have.

## Solution idea(s)
One simple format can be:
Namespace/Class/Node/ActionType/ActionName/ActionValue

**Comment by jonlouie** [comment]
Sticking with JSON based rules- can reopen if needed
